### ISSUE TITLE
sunrise-commander breaks other-window on emacs feature/native-comp branch

### ISSUE THREAD

**Issue by peterpaul** [sunrise-commander/sunrise-commander#108]
Thanks for this awesome software package. I regularly use this (in combination with TRAMP) to move files to/from my laptop and my storage server.

Recently I started experimenting with the `feature/native-comp` branch of emacs, and I noticed that the `other-window` function isn't working when called interactively (`C-x o`). I traced it back to sunrise-commander. Not sure if the problem is in sunrise-commander or on the `native-comp` branch.

I get the following backtrace, this is on a clean emacs with only sunrise-commander.el loaded.

```
Debugger entered--Lisp error: (wrong-number-of-arguments #f(compiled-function (ad--addoit-function count &optional all-frames) #<bytecode 0x1c8131fdfe1321c8>) 4)
  ad-Advice-other-window(#<subr other-window> 1 nil 1)
  apply(ad-Advice-other-window #<subr other-window> (1 nil 1))
  other-window(1 nil 1)
  funcall-interactively(other-window 1 nil 1)
  command-execute(other-window)
```

From this I can understand that it has something to do with the `(defadvice other-window ...)` in sunrise-commander.el, but I lack further knowledge.

Edit: The expanded lisp error is:

```
(wrong-number-of-arguments
 (lambda
   (ad--addoit-function count &optional all-frames)
   (let
       (ad-return-value)
     (progn
       (if
	   (or
	    (not sr-running)
	    sr-ediff-on)
	   (setq ad-return-value
		 (with-no-warnings
		   (funcall ad--addoit-function count all-frames nil)))
	 (let
	     ((from \.\.\.)
	      (to \.\.\.))
	   (if
	       (or sr-traditional-other-window \.\.\. \.\.\.)
	       (setq ad-return-value \.\.\.)
	     (sr-select-window sr-selected-window))))
       (sr-detect-switch))
     ad-return-value))
 4)
```

**Comment by lassik** [comment]
Thanks for reporting this! I can't tell right away what causes the bug - `other-window` works fine for me. Are you using a recent nativecomp commit from this year?

It looks like the `lambda` is expecting 3 arguments (the last of which is optional) whereas it's being called with 4 args, so one extra.

**Comment by lassik** [comment]
Try `C-h f other-window` -- what does the help say is the argument list for `other-window` on your Emacs version?

For Emacs 27.1 (non-nativecomp) the arglist is `(other-window COUNT &optional ALL-FRAMES)`.

**Comment by peterpaul** [comment]
I compiled emacs today, the last commit is:

```
99638d128e feature/native-comp origin/feature/native-comp ; * src/comp.c (Fcomp__compile_ctxt_to_file) [WINDOWSNT]: Fix last change.
```

`about-emacs` shows `GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0)
 of 2021-03-07`

Indeed the argument list is different for me: `(other-window COUNT &optional ALL-FRAMES INTERACTIVE)`

**Comment by lassik** [comment]
Interesting. Your arglist is the one that it has in SC's source code though. Hmm. In the above PR, I removed any mention of the arglist in the place where we define the advice. Can you check whether it fixes the bug for you? I don't really know what I'm doing but by default Emacs should use the arglist from the advised function if we don't give an arglist ourselves.

**Comment by peterpaul** [comment]
Hmmm, on my machine the `interactive` argument was not in the `defadvice` line.
When I add that, it works properly.

It also seems to work when I apply your patch.

**Comment by lassik** [comment]
Good to know. If the patch works, that's probably the best way to do it: since Sunrise doesn't need to consult any of the arguments given to `other-window`, it's simplest to let Emacs use its defaults.

**Comment by lassik** [comment]
I merged the patch to master. Let us know if you still get the problem in the future.
