### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by kensanata** [sunrise-commander/sunrise-commander#53]
The [homepage](http://joseito.republika.pl/sunrise-commander/) shows how to setup ELPA. We should change the HTTP links to HTTPS, and add HTTPS support to joseito.republika.pl using [Let's Encrypt](https://letsencrypt.org/).

**Comment by zabbal** [comment]
This might be made obsolete depending on how #57 is resolved.

**Comment by lassik** [comment]
Closing this since the ELPA repo is no longer live.
