### ISSUE TITLE
Put faces into a sub customization group

### ISSUE THREAD

**Issue by rusimody** [sunrise-commander/sunrise-commander#56]
Hi José!
it would be nice if all the faces were grouped separately from other options
Here's a patch
[patch.txt](https://github.com/sunrise-commander/sunrise-commander/files/1584898/patch.txt)

**Comment by lassik** [comment]
@rusimody Thanks for the patch!

@zonuexe I think we should follow whatever the general Emacs convention is. If the convention is to put faces in their own group, let's do it.

**Comment by zonuexe** [comment]
OK, that's right.

**Comment by lassik** [comment]
Implemented in PR #95
