### ISSUE TITLE
Is the ELPA repository at http://joseito.republika.pl/sunrise-commander/ working?

### ISSUE THREAD

**Issue by evolve75** [sunrise-commander/sunrise-commander#57]
Hello!

For the last few weeks (starting April 2018?), the [ELPA repository](http://joseito.republika.pl/sunrise-commander/) for `sunrise-commander` is throwing errors. Is it active now?

**Comment by escherdragon** [comment]
Unfortunately the hosting service from which the code was being served was closed at the beginning of the month. I'm currently looking for a new home for the repository. In the meantime simply use [the copies in the Emacs Wiki](https://www.emacswiki.org/emacs/Sunrise_Commander), they're up-to-date. I'm leaving this issue open and will close it as soon as a new ELPA repository is up and running.

**Comment by osmoc** [comment]
It might make sense to update https://www.emacswiki.org/emacs/Sunrise_Commander which still has outdated link in it. Would it be possible to put it directly to ELPA or MELPA?

**Comment by zabbal** [comment]
I'd second the last question - are there any issues preventing from adding SC to (M)ELPA? This project definitely deserves wider adoption.

**Comment by lassik** [comment]
Closing this for now to focus on submitting SC into MELPA. We can re-open this issue later if it makes sense to go back to a dedicated SC ELPA repo.
