### ISSUE TITLE
Can you remove   (set (make-local-variable 'dired-recursive-deletes) 'top), please?

### ISSUE THREAD

**Issue by breadncup** [sunrise-commander/sunrise-commander#60]
Could you remove

  (set (make-local-variable 'dired-recursive-deletes) 'top)
, please?

Please, respect the original dired behavior for the recursive deletion of directories.

**Comment by lassik** [comment]
@breadncup Do you mean that SC should respect the user's choice of `dired-recursive-deletes`, whatever that choice is? I think that sounds good. Does @zonuexe agree?

@escherdragon Is there a particular reason SC always sets `dired-recursive-deletes` to `top`?

**Comment by lassik** [comment]
Fixed by @zonuexe in #94.
