### ISSUE TITLE
How to go to end of line

### ISSUE THREAD

**Issue by raxod502** [sunrise-commander/sunrise-commander#61]
Normally in Emacs/Dired, `C-e` is bound to `move-end-of-line`. This is useful, for example, when a filename is long enough to scroll past the edge of the window. Why does Sunrise Commander rebind `C-e` to something different, and what's the intended workaround (besides typing `M-x move-end-of-line`)?

**Comment by vspinu** [comment]
I am rebinding navigation commands. I also think it's a bad citizenship to mess with basic navigation commands. 


```
         ("C-e" . nil)
         ("M-f" . nil)
         ("C-n" . nil)
         ("C-p" . nil)
         ("C-j" . nil)
         ("C-c t" . nil)
```

**Comment by lassik** [comment]
Thanks for getting on board @vspinu and thanks for keeping in touch @raxod502!

Since the topic is getting quite complicated, let's merge this discussion into issue #80 and continue there. I'll close this one.
