### ISSUE TITLE
Rewrite sunrise-fuzzy-narrow using `invisible` text property

### ISSUE THREAD

**Issue by raxod502** [sunrise-commander/sunrise-commander#62]
Like the title says. I get this after I do a fuzzy narrow in my home directory for `trash` using `sr-fuzzy-narrow`. This is from `emacs -Q` using revision a98c5c77e6d49d906919f4a9ab6192ea391a5255 of Sunrise Commander.

![image](https://user-images.githubusercontent.com/6559064/43997124-9213a52c-9da1-11e8-96dd-4230cdcbacda.png)

```
  /Users/raxod502:
  total used in directory 1528 available 18502059
  drwx------  6068 raxod502  staff  206312 Aug 11 19:57 .Trash
! lrwxr-xr-x     1 raxod502  staff      58 Jun 25 17:30 .mbsyncrc -> /Users/raxod502/files/control/radian-local/isync/.mbsyncrc
```

**Comment by lassik** [comment]
Thanks for the bug report @raxod502. Can you be more specific about what the correct behavior should be - should that symlink's target path be hidden completely, or should it be shown in some different way?

**Comment by raxod502** [comment]
This isn't related to whether the target path of the symlink should be shown. My point is that if I've typed in `trash`, then `.mbsyncrc` shouldn't be shown as it has nothing to do with `trash`. There's a bug in the filtering algorithm.

**Comment by lassik** [comment]
I see. I'm not familiar with `sunrise-fuzzy-narrow` but its implementation seems to rely on dired to hide the files:

```
(dired-mark-files-regexp (concat "^" regex "$"))
(dired-toggle-marks)
(dired-do-kill-lines)
```

where `regex` is arrived at in a complex manner. We should probably insert a `(message "%S" regex)` statement somewhere in the loop to find out what regexps it gets.

**Comment by raxod502** [comment]
Dired probably doesn't bother to mark files if they don't "exist".

**Comment by lassik** [comment]
It does. You can confirm by running `ln -s nonexistent foo` and trying to mark `foo`.

**Comment by lassik** [comment]
I added the following debugging line to `sunrise-fuzzy-narrow`:

```
          (when next-char
            (message "sunrise-fuzzy-narrow: %S" regex)  ; debug
            (dired-mark-files-regexp (concat "^" regex "$"))
```

When narrowing into `trash` one letter at a time, this is what it does:

```
sunrise-fuzzy-narrow: ".*t.*"
Marking matching files...
0 matching files marked.
Killed 0 lines.
sunrise-fuzzy-narrow: ".*t.*r.*"
Marking matching files...
0 matching files marked.
Killed 0 lines.
sunrise-fuzzy-narrow: ".*t.*r.*a.*"
Marking matching files...
0 matching files marked.
Killed 0 lines.
sunrise-fuzzy-narrow: ".*t.*r.*a.*s.*"
Marking matching files...
0 matching files marked.
Killed 0 lines.
sunrise-fuzzy-narrow: ".*t.*r.*a.*s.*h.*"
Marking matching files...
0 matching files marked.
Killed 0 lines.
```

**Comment by lassik** [comment]
`dired-toggle-marks` works as expected (at least when calling it interactively)

**Comment by lassik** [comment]
...though there's something funny with it behaving in different ways at different times (even without sunrise). Using marks and killling lines to hide files is a bit of a hacky implementation technique to begin with. Dired has a `dired-omit-files` regexp that can be used to hide files on is not interested in. We need to be in `dired-omit-mode` for it to have an effect.

The only problem is that the user should be able to have their own `dired-omit-files` regexp in addition to the sunrise-fuzzy-narrow regexp. So we'd have to be able to reliably make a new regexp that matches either the old `dired-omit-files` or the complement of the fuzzy-narrow regexp. @zonuexe What do you think about this approach?

**Comment by lassik** [comment]
https://melpa.org/#/dired-narrow | https://github.com/Fuco1/dired-hacks/tree/master

**Comment by lassik** [comment]
Should be fixed in the above commit.

**Comment by lassik** [comment]
@raxod502 That PR is now merged into master, so this issue should be solved. Please let us know if the problem persists.
