### ISSUE TITLE
Temporary ELPA repo for testing packages before we submit to MELPA

### ISSUE THREAD

**Issue by lassik** [sunrise-commander/sunrise-commander#72]
@zonuexe Do you know how to set up a custom repo for `package.el`?

Since SC is complex and the MELPA maintainers are very busy, I think we should first make a temporary package repo that contains only our SC package(s). That way, we can experiment with packaging approaches (have SC and all extensions in one big bundle package, vs have each extension in its own package) and fix major bugs before we submit SC to review by MELPA.

I got the impression that package.el just needs a few static files on the server - is this true? I can easily arrange a web server, DNS and/or ssh account if needed.

**Comment by zonuexe** [comment]
I don't think SunriseCommander's specific package repository is necessary. Maybe there is a way to build a repository using only GitHub Pages, but I do not recommend it.

Alternatively, users can install directly from GitHub with one of the package managers, such as [Cask](https://cask.github.io/), [straight.el](https://github.com/raxod502/straight.el), [El-Get](https://github.com/dimitri/el-get), [Quelpa](https://framagit.org/steckerhalter/quelpa).

Also, we developers can load the packages we built ourselves.

```el
(when (file-directory-p "~/repo/emacs/sunrise-commander")
  (load "~/repo/emacs/sunrise-commander/sunrise-commander-autoloads.el"))
```

This is equivalent to the process of initializing the autoload file generated by the package manager.

**Comment by lassik** [comment]
Thanks for explaining it. My packages have been so simple so far that I've got by with M-x byte-compile-file. It may be enough just to use the tools you suggest.

Hey, org-mode's own ELPA repo provides a very clear example of what the server side looks like: https://orgmode.org/elpa/

**Comment by lassik** [comment]
It's starting to seem that this is overkill. I'll close the issue; we can re-open it later if we need a repo.
