### ISSUE TITLE
Set sunrise-buttons-command-adapter in sunrise-tree.el

### ISSUE THREAD

**Issue by lassik** [sunrise-commander/sunrise-commander#90]
Currently in `sunrise-tree.el`:

```
;; TODO: This does not have the`sunrise-tree-` prefix. Figure out how to solve.
(defvar sunrise-buttons-command-adapter nil
  "Compiler pacifier.
See `sunrise-buttons-command-adapter' in sunrise-buttons.el.")
```

The `sunrise-tree-mode` initialization uses it:

```
(define-derived-mode sunrise-tree-mode nil "Sunrise Tree View"
  ...
  (mapc 'make-local-variable '(... sunrise-buttons-command-adapter))
  ...
  (setq ...
        sunrise-buttons-command-adapter 'sunrise-tree-buttons-command-adapter)
  ...)
```

We should clearly get rid of the `(defvar sunrise-buttons-command-adapter ...)` shim, but how? I tried `(set 'sunrise-buttons-command-adapter ...)` instead of `(setq sunrise-buttons-command-adapter ...)` and it produces the same warning.

Can we use `(setf (symbol-value 'sunrise-buttons-command-adapter) ...)`? We need to set the buffer-local binding. Does `setf symbol-value` set the buffer-local or the global binding?

**Comment by lassik** [comment]
@zonuexe Do you have any ideas for solving this?

**Comment by lassik** [comment]
I suppose normally we'd just list sunrise-buttons as a dependency for sunrise-tree. But since it's an _optional_ dependency that sunrise-tree also works without, that's where the problem comes from.

**Comment by zonuexe** [comment]
@lassik 
I recommend removing `(defvar sunrise-buttons-command-adapter)` from `sunrise-tree.el` and adding `(require 'sunrise-buttons)`. Because it's a relatively small file feature, you don't have to worry about performance degradation.

**Comment by zonuexe** [comment]
@lassik 
I missed the following comment https://github.com/sunrise-commander/sunrise-commander/issues/90#issuecomment-523332471.

A better way to avoid compiler and Linter warnings is to guard with `boundp`.

```diff
@@ -919,15 +914,17 @@ Moves files from the active pane to the passive pane."
                                isearch-mode-end-hook
                                desktop-save-buffer
                                revert-buffer-function
-                               sunrise-goto-dir-function
-                               sunrise-buttons-command-adapter))
+                               sunrise-goto-dir-function))
   (add-hook 'isearch-mode-end-hook 'sunrise-tree-update-cursor)
   (setq desktop-save-buffer        'sunrise-tree-desktop-save-buffer
         hl-line-sticky-flag        nil
         revert-buffer-function     'sunrise-tree-revert-buffer
-        sunrise-goto-dir-function       'sunrise-tree-goto-dir
-        sunrise-buttons-command-adapter 'sunrise-tree-buttons-command-adapter)
+        sunrise-goto-dir-function       'sunrise-tree-goto-dir)
   (setq dired-omit-mode t)
+
+  (when (boundp 'sunrise-buttons-command-adapter)
+    (setq-local sunrise-buttons-command-adapter 'sunrise-tree-buttons-command-adapter))
+
   (set (make-local-variable 'buffer-quit-function) 'sunrise-quit)
   (set (make-local-variable 'track-mouse) sunrise-cursor-follows-mouse)
   (hl-line-mode 1)
```

**Comment by lassik** [comment]
Great! I had no idea the compiler is smart enough to detect `(when (boundp) ...)` and behave differently. Your patch is the best way to solve it.
