### ISSUE TITLE
Update Package-Requires lines in extensions

### ISSUE THREAD

**Issue by lassik** [sunrise-commander/sunrise-commander#93]
Currently all our `.el` files just say:

` Package-Requires: ((emacs "24.3") (cl-lib "0.5"))`

We should update those lines to include any third-party packages required by extensions.

**Comment by lassik** [comment]
Full list of requires:

```
File: sunrise-modeline.el
(require 'desktop)
(require 'easymenu)

File: sunrise-buttons.el
(require 'cus-edit)

File: sunrise-checkpoint.el
(require 'bookmark)

File: sunrise-tree.el
(require 'tree-widget)
(require 'hl-line)

File: sunrise.el
(require 'advice)
(require 'desktop)
(require 'dired)
(require 'dired-aux)
(require 'dired-x)
(require 'enriched)
(require 'esh-mode)
(require 'find-dired)
(require 'font-lock)
(require 'hl-line)
(require 'sort)
(require 'term)
(require 'tramp)
```

**Comment by lassik** [comment]
All of these come standard with Emacs. Should we still add them in `Package-Requires`?

**Comment by zonuexe** [comment]
@lassik 
Thank you for listing the dependent features!

All of these features are bundled and do not need to be added to `Package-Requires`.

**Comment by lassik** [comment]
Great. However, it's customary to list `cl-lib` in `Package-Requires` even though `cl-lib` also comes with Emacs (at least in the current version). Is there a reason for that?

**Comment by zonuexe** [comment]
@lassik It is by convention, but we can omit it.

**Comment by lassik** [comment]
If there's a widespread convention among MELPA packages to include it, I guess we should follow that even if it's not strictly necessary with new versions of Emacs.

**Comment by lassik** [comment]
OK, let's follow the convention and include `cl-lib`.
